<?php
namespace Common\Controller;

/**
 * 基类Controller
 */
class IndexBaseController extends BaseController
{
	public $ERROR_CODE_COMMON =array();         // 公共返回码
    public $ERROR_CODE_COMMON_ZH =array();      // 公共返回码中文描述
    public $ERROR_CODE_USER =array();           // 用户相关返回码
    public $ERROR_CODE_USER_ZH =array();        // 用户相关返回码中文描述
    public $ERROR_CODE_RESULT =array();         // 作业相关返回码
    public $ERROR_CODE_RESULT_ZH =array();      // 作业相关返回码中文描述
	/**
	 * 初始化方法
	 */
	public function _initialize(){
		parent::_initialize();
		// 返回码配置
        $this->ERROR_CODE_COMMON = json_decode(error_code_common,true);
        $this->ERROR_CODE_COMMON_ZH = json_decode(error_code_common_zh,true);
        $this->ERROR_CODE_USER = json_decode(error_code_user,true);
        $this->ERROR_CODE_USER_ZH = json_decode(error_code_user_zh,true);
        $this->ERROR_CODE_RESULT = json_decode(error_code_result,true);
        $this->ERROR_CODE_RESULT_ZH = json_decode(error_code_result_zh,true);
	}

	public function __construct(){
        parent::__construct();
        if(!$_SESSION['user_info']['id']){
            $this->error('请先登录系统！',U('Login/login'));
        }

        if(!(MODULE_NAME == "Index"&&CONTROLLER_NAME=="Upload"&&ACTION_NAME=="claimed_file")){
            // 判断用户是否有所属公司
            $user = new \Common\Model\UserModel();
            $firmid = $user->getFieldById($_SESSION['user_info']['id'],'firmid');
            if ($firmid == '') {
                $this->error('请完善信息',U('Login/perfect'));
            }
        }
    }

/*    function display($templateFile = '', $charset = '', $contentType = '', $content = '', $prefix = '')
    {
        header('Content-Type:application/json; charset=utf-8');
//        parent::display($templateFile, $charset, $contentType, $content, $prefix); // TODO: Change the autogenerated stub
        exit(json_encode($this->get()));
    }

    function success($message = '', $jumpUrl = '', $ajax = false, $code = 1)
    {
        $this->dispatchJump($message, $code, $jumpUrl, $ajax);
    }

    function dispatchJump($message, $status = 1, $jumpUrl = '', $ajax = false)
    {
        if (true === $ajax || IS_AJAX) {// AJAX提交
            $data = is_array($ajax) ? $ajax : array();
            $data['info'] = $message;
            $data['code'] = $status;
            $data['url'] = $jumpUrl;
            $this->ajaxReturn($data);
        }
        if (is_int($ajax)) $this->assign('waitSecond', $ajax);
        if (!empty($jumpUrl)) $this->assign('jumpUrl', $jumpUrl);
        // 提示标题
        $this->assign('msgTitle', $status ? L('_OPERATION_SUCCESS_') : L('_OPERATION_FAIL_'));
        //如果设置了关闭窗口，则提示完毕后自动关闭窗口
        if ($this->get('closeWin')) $this->assign('jumpUrl', 'javascript:window.close();');
        $this->assign('code', $status);   // 状态
        //保证输出不受静态缓存影响
        C('HTML_CACHE_ON', false);
        if ($status == 1) { //发送成功信息
            $this->assign('message', $message);// 提示信息
            // 成功操作后默认停留1秒
            if (!isset($this->waitSecond)) $this->assign('waitSecond', '1');
            // 默认操作成功自动返回操作前页面
            if (!isset($this->jumpUrl)) $this->assign("jumpUrl", $_SERVER["HTTP_REFERER"]);
            $this->display(C('TMPL_ACTION_SUCCESS'));
        } else {
            $this->assign('error', $message);// 提示信息
            //发生错误时候默认停留3秒
            if (!isset($this->waitSecond)) $this->assign('waitSecond', '3');
            // 默认发生错误的话自动返回上页
            if (!isset($this->jumpUrl)) $this->assign('jumpUrl', "javascript:history.back(-1);");
            $this->display(C('TMPL_ACTION_ERROR'));
            // 中止执行  避免出错后继续执行
            exit;
        }
    }

    function error($message = '', $jumpUrl = '', $ajax = false,$code=25565)
    {
        $this->dispatchJump($message, $code, $jumpUrl, $ajax);
    }*/
}