<?php
namespace Index\Controller;
use Think\Controller;

class ArticleController extends Controller 
{
    // 定义数据表
    private $db;

    // 构造函数 实例化ArticleModel表
    public function __construct(){
        parent::__construct();
        $this->db = new \Common\Model\ArticleModel();
    }

    /**
     * 查看资讯信息
     */
    public function msg(){
        $aid=I('get.aid');
        $data=$this->db->getDataByAid($aid,1);
        $this->assign('data',$data);
        $this->display();
    }

    function display($templateFile = '', $charset = '', $contentType = '', $content = '', $prefix = '')
    {
        header('Content-Type:application/json; charset=utf-8');
//        parent::display($templateFile, $charset, $contentType, $content, $prefix); // TODO: Change the autogenerated stub
        exit(json_encode($this->get()));
    }

    function success($message = '', $jumpUrl = '', $ajax = false, $code = 1)
    {
        $this->dispatchJump($message, $code, $jumpUrl, $ajax);
    }

    function dispatchJump($message, $status = 1, $jumpUrl = '', $ajax = false)
    {
        if (true === $ajax || IS_AJAX) {// AJAX提交
            $data = is_array($ajax) ? $ajax : array();
            $data['info'] = $message;
            $data['code'] = $status;
            $data['url'] = $jumpUrl;
            $this->ajaxReturn($data);
        }
        if (is_int($ajax)) $this->assign('waitSecond', $ajax);
        if (!empty($jumpUrl)) $this->assign('jumpUrl', $jumpUrl);
        // 提示标题
        $this->assign('msgTitle', $status ? L('_OPERATION_SUCCESS_') : L('_OPERATION_FAIL_'));
        //如果设置了关闭窗口，则提示完毕后自动关闭窗口
        if ($this->get('closeWin')) $this->assign('jumpUrl', 'javascript:window.close();');
        $this->assign('code', $status);   // 状态
        //保证输出不受静态缓存影响
        C('HTML_CACHE_ON', false);
        if ($status == 1) { //发送成功信息
            $this->assign('message', $message);// 提示信息
            // 成功操作后默认停留1秒
            if (!isset($this->waitSecond)) $this->assign('waitSecond', '1');
            // 默认操作成功自动返回操作前页面
            if (!isset($this->jumpUrl)) $this->assign("jumpUrl", $_SERVER["HTTP_REFERER"]);
            $this->display(C('TMPL_ACTION_SUCCESS'));
        } else {
            $this->assign('error', $message);// 提示信息
            //发生错误时候默认停留3秒
            if (!isset($this->waitSecond)) $this->assign('waitSecond', '3');
            // 默认发生错误的话自动返回上页
            if (!isset($this->jumpUrl)) $this->assign('jumpUrl', "javascript:history.back(-1);");
            $this->display(C('TMPL_ACTION_ERROR'));
            // 中止执行  避免出错后继续执行
            exit;
        }
    }

    function error($message = '', $jumpUrl = '', $ajax = false,$code=25565)
    {
        $this->dispatchJump($message, $code, $jumpUrl, $ajax);
    }
}